name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # releaser-tool 不会自动为依赖项添加存储库，需要在运行 releaser 之前将其添加到管道
      - name: Add Helm dependencies
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add cert-manager https://charts.jetstack.io
          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
          helm repo add kong https://charts.konghq.com

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
